// Code generated by protoc-gen-go. DO NOT EDIT.
// source: menu.proto

package restaurant_restaurant

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Menu struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EntityId             string   `protobuf:"bytes,2,opt,name=entity_id,proto3" json:"entity_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,5,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Menu) Reset()         { *m = Menu{} }
func (m *Menu) String() string { return proto.CompactTextString(m) }
func (*Menu) ProtoMessage()    {}
func (*Menu) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{0}
}

func (m *Menu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Menu.Unmarshal(m, b)
}
func (m *Menu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Menu.Marshal(b, m, deterministic)
}
func (m *Menu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Menu.Merge(m, src)
}
func (m *Menu) XXX_Size() int {
	return xxx_messageInfo_Menu.Size(m)
}
func (m *Menu) XXX_DiscardUnknown() {
	xxx_messageInfo_Menu.DiscardUnknown(m)
}

var xxx_messageInfo_Menu proto.InternalMessageInfo

func (m *Menu) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Menu) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

func (m *Menu) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Menu) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Menu) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type Category struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MenuId               string   `protobuf:"bytes,2,opt,name=menu_id,proto3" json:"menu_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,6,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{1}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Category) GetMenuId() string {
	if m != nil {
		return m.MenuId
	}
	return ""
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Category) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Category) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type Item struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId           string   `protobuf:"bytes,2,opt,name=category_id,proto3" json:"category_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl             string   `protobuf:"bytes,5,opt,name=image_url,proto3" json:"image_url,omitempty"`
	Price                int32    `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	CreatedAt            string   `protobuf:"bytes,7,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,8,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{2}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetCategoryId() string {
	if m != nil {
		return m.CategoryId
	}
	return ""
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Item) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *Item) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Item) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Item) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type CreateMenuRequest struct {
	EntityId             string   `protobuf:"bytes,1,opt,name=entity_id,proto3" json:"entity_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMenuRequest) Reset()         { *m = CreateMenuRequest{} }
func (m *CreateMenuRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMenuRequest) ProtoMessage()    {}
func (*CreateMenuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{3}
}

func (m *CreateMenuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMenuRequest.Unmarshal(m, b)
}
func (m *CreateMenuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMenuRequest.Marshal(b, m, deterministic)
}
func (m *CreateMenuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMenuRequest.Merge(m, src)
}
func (m *CreateMenuRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMenuRequest.Size(m)
}
func (m *CreateMenuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMenuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMenuRequest proto.InternalMessageInfo

func (m *CreateMenuRequest) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

func (m *CreateMenuRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateMenuResponse struct {
	Menu                 *Menu    `protobuf:"bytes,1,opt,name=menu,proto3" json:"menu,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMenuResponse) Reset()         { *m = CreateMenuResponse{} }
func (m *CreateMenuResponse) String() string { return proto.CompactTextString(m) }
func (*CreateMenuResponse) ProtoMessage()    {}
func (*CreateMenuResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{4}
}

func (m *CreateMenuResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMenuResponse.Unmarshal(m, b)
}
func (m *CreateMenuResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMenuResponse.Marshal(b, m, deterministic)
}
func (m *CreateMenuResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMenuResponse.Merge(m, src)
}
func (m *CreateMenuResponse) XXX_Size() int {
	return xxx_messageInfo_CreateMenuResponse.Size(m)
}
func (m *CreateMenuResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMenuResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMenuResponse proto.InternalMessageInfo

func (m *CreateMenuResponse) GetMenu() *Menu {
	if m != nil {
		return m.Menu
	}
	return nil
}

type UpdateMenuRequest struct {
	MenuId               string   `protobuf:"bytes,1,opt,name=menu_id,proto3" json:"menu_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMenuRequest) Reset()         { *m = UpdateMenuRequest{} }
func (m *UpdateMenuRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMenuRequest) ProtoMessage()    {}
func (*UpdateMenuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{5}
}

func (m *UpdateMenuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMenuRequest.Unmarshal(m, b)
}
func (m *UpdateMenuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMenuRequest.Marshal(b, m, deterministic)
}
func (m *UpdateMenuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMenuRequest.Merge(m, src)
}
func (m *UpdateMenuRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateMenuRequest.Size(m)
}
func (m *UpdateMenuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMenuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMenuRequest proto.InternalMessageInfo

func (m *UpdateMenuRequest) GetMenuId() string {
	if m != nil {
		return m.MenuId
	}
	return ""
}

func (m *UpdateMenuRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateMenuResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMenuResponse) Reset()         { *m = UpdateMenuResponse{} }
func (m *UpdateMenuResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateMenuResponse) ProtoMessage()    {}
func (*UpdateMenuResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{6}
}

func (m *UpdateMenuResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMenuResponse.Unmarshal(m, b)
}
func (m *UpdateMenuResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMenuResponse.Marshal(b, m, deterministic)
}
func (m *UpdateMenuResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMenuResponse.Merge(m, src)
}
func (m *UpdateMenuResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateMenuResponse.Size(m)
}
func (m *UpdateMenuResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMenuResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMenuResponse proto.InternalMessageInfo

type DeleteMenuRequest struct {
	MenuId               string   `protobuf:"bytes,1,opt,name=menu_id,proto3" json:"menu_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMenuRequest) Reset()         { *m = DeleteMenuRequest{} }
func (m *DeleteMenuRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMenuRequest) ProtoMessage()    {}
func (*DeleteMenuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{7}
}

func (m *DeleteMenuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMenuRequest.Unmarshal(m, b)
}
func (m *DeleteMenuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMenuRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMenuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMenuRequest.Merge(m, src)
}
func (m *DeleteMenuRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMenuRequest.Size(m)
}
func (m *DeleteMenuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMenuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMenuRequest proto.InternalMessageInfo

func (m *DeleteMenuRequest) GetMenuId() string {
	if m != nil {
		return m.MenuId
	}
	return ""
}

type DeleteMenuResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMenuResponse) Reset()         { *m = DeleteMenuResponse{} }
func (m *DeleteMenuResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteMenuResponse) ProtoMessage()    {}
func (*DeleteMenuResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{8}
}

func (m *DeleteMenuResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMenuResponse.Unmarshal(m, b)
}
func (m *DeleteMenuResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMenuResponse.Marshal(b, m, deterministic)
}
func (m *DeleteMenuResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMenuResponse.Merge(m, src)
}
func (m *DeleteMenuResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteMenuResponse.Size(m)
}
func (m *DeleteMenuResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMenuResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMenuResponse proto.InternalMessageInfo

type GetMenuRequest struct {
	EntityId             string   `protobuf:"bytes,1,opt,name=entity_id,proto3" json:"entity_id,omitempty"`
	MenuId               string   `protobuf:"bytes,2,opt,name=menu_id,proto3" json:"menu_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMenuRequest) Reset()         { *m = GetMenuRequest{} }
func (m *GetMenuRequest) String() string { return proto.CompactTextString(m) }
func (*GetMenuRequest) ProtoMessage()    {}
func (*GetMenuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{9}
}

func (m *GetMenuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMenuRequest.Unmarshal(m, b)
}
func (m *GetMenuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMenuRequest.Marshal(b, m, deterministic)
}
func (m *GetMenuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMenuRequest.Merge(m, src)
}
func (m *GetMenuRequest) XXX_Size() int {
	return xxx_messageInfo_GetMenuRequest.Size(m)
}
func (m *GetMenuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMenuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMenuRequest proto.InternalMessageInfo

func (m *GetMenuRequest) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

func (m *GetMenuRequest) GetMenuId() string {
	if m != nil {
		return m.MenuId
	}
	return ""
}

type GetMenuResponse struct {
	Menu                 *Menu    `protobuf:"bytes,1,opt,name=menu,proto3" json:"menu,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMenuResponse) Reset()         { *m = GetMenuResponse{} }
func (m *GetMenuResponse) String() string { return proto.CompactTextString(m) }
func (*GetMenuResponse) ProtoMessage()    {}
func (*GetMenuResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{10}
}

func (m *GetMenuResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMenuResponse.Unmarshal(m, b)
}
func (m *GetMenuResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMenuResponse.Marshal(b, m, deterministic)
}
func (m *GetMenuResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMenuResponse.Merge(m, src)
}
func (m *GetMenuResponse) XXX_Size() int {
	return xxx_messageInfo_GetMenuResponse.Size(m)
}
func (m *GetMenuResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMenuResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMenuResponse proto.InternalMessageInfo

func (m *GetMenuResponse) GetMenu() *Menu {
	if m != nil {
		return m.Menu
	}
	return nil
}

type AddCategoryRequest struct {
	MenuId               string   `protobuf:"bytes,1,opt,name=menu_id,proto3" json:"menu_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCategoryRequest) Reset()         { *m = AddCategoryRequest{} }
func (m *AddCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*AddCategoryRequest) ProtoMessage()    {}
func (*AddCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{11}
}

func (m *AddCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCategoryRequest.Unmarshal(m, b)
}
func (m *AddCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCategoryRequest.Marshal(b, m, deterministic)
}
func (m *AddCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCategoryRequest.Merge(m, src)
}
func (m *AddCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_AddCategoryRequest.Size(m)
}
func (m *AddCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCategoryRequest proto.InternalMessageInfo

func (m *AddCategoryRequest) GetMenuId() string {
	if m != nil {
		return m.MenuId
	}
	return ""
}

func (m *AddCategoryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddCategoryResponse struct {
	Category             *Category `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddCategoryResponse) Reset()         { *m = AddCategoryResponse{} }
func (m *AddCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*AddCategoryResponse) ProtoMessage()    {}
func (*AddCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{12}
}

func (m *AddCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCategoryResponse.Unmarshal(m, b)
}
func (m *AddCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCategoryResponse.Marshal(b, m, deterministic)
}
func (m *AddCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCategoryResponse.Merge(m, src)
}
func (m *AddCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_AddCategoryResponse.Size(m)
}
func (m *AddCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddCategoryResponse proto.InternalMessageInfo

func (m *AddCategoryResponse) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

type UpdateCategoryRequest struct {
	CategoryId           string   `protobuf:"bytes,1,opt,name=category_id,proto3" json:"category_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCategoryRequest) Reset()         { *m = UpdateCategoryRequest{} }
func (m *UpdateCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCategoryRequest) ProtoMessage()    {}
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{13}
}

func (m *UpdateCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCategoryRequest.Unmarshal(m, b)
}
func (m *UpdateCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCategoryRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCategoryRequest.Merge(m, src)
}
func (m *UpdateCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCategoryRequest.Size(m)
}
func (m *UpdateCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCategoryRequest proto.InternalMessageInfo

func (m *UpdateCategoryRequest) GetCategoryId() string {
	if m != nil {
		return m.CategoryId
	}
	return ""
}

func (m *UpdateCategoryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateCategoryResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCategoryResponse) Reset()         { *m = UpdateCategoryResponse{} }
func (m *UpdateCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCategoryResponse) ProtoMessage()    {}
func (*UpdateCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{14}
}

func (m *UpdateCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCategoryResponse.Unmarshal(m, b)
}
func (m *UpdateCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCategoryResponse.Marshal(b, m, deterministic)
}
func (m *UpdateCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCategoryResponse.Merge(m, src)
}
func (m *UpdateCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCategoryResponse.Size(m)
}
func (m *UpdateCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCategoryResponse proto.InternalMessageInfo

type DeleteCategoryRequest struct {
	CategoryId           string   `protobuf:"bytes,1,opt,name=category_id,proto3" json:"category_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCategoryRequest) Reset()         { *m = DeleteCategoryRequest{} }
func (m *DeleteCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCategoryRequest) ProtoMessage()    {}
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{15}
}

func (m *DeleteCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCategoryRequest.Unmarshal(m, b)
}
func (m *DeleteCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCategoryRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCategoryRequest.Merge(m, src)
}
func (m *DeleteCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCategoryRequest.Size(m)
}
func (m *DeleteCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCategoryRequest proto.InternalMessageInfo

func (m *DeleteCategoryRequest) GetCategoryId() string {
	if m != nil {
		return m.CategoryId
	}
	return ""
}

type DeleteCategoryResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCategoryResponse) Reset()         { *m = DeleteCategoryResponse{} }
func (m *DeleteCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCategoryResponse) ProtoMessage()    {}
func (*DeleteCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{16}
}

func (m *DeleteCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCategoryResponse.Unmarshal(m, b)
}
func (m *DeleteCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCategoryResponse.Marshal(b, m, deterministic)
}
func (m *DeleteCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCategoryResponse.Merge(m, src)
}
func (m *DeleteCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCategoryResponse.Size(m)
}
func (m *DeleteCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCategoryResponse proto.InternalMessageInfo

type ListCategoryRequest struct {
	MenuId               string   `protobuf:"bytes,1,opt,name=menu_id,proto3" json:"menu_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCategoryRequest) Reset()         { *m = ListCategoryRequest{} }
func (m *ListCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*ListCategoryRequest) ProtoMessage()    {}
func (*ListCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{17}
}

func (m *ListCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCategoryRequest.Unmarshal(m, b)
}
func (m *ListCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCategoryRequest.Marshal(b, m, deterministic)
}
func (m *ListCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCategoryRequest.Merge(m, src)
}
func (m *ListCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_ListCategoryRequest.Size(m)
}
func (m *ListCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCategoryRequest proto.InternalMessageInfo

func (m *ListCategoryRequest) GetMenuId() string {
	if m != nil {
		return m.MenuId
	}
	return ""
}

type ListCategoryResponse struct {
	Categories           []*Category `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListCategoryResponse) Reset()         { *m = ListCategoryResponse{} }
func (m *ListCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*ListCategoryResponse) ProtoMessage()    {}
func (*ListCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{18}
}

func (m *ListCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCategoryResponse.Unmarshal(m, b)
}
func (m *ListCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCategoryResponse.Marshal(b, m, deterministic)
}
func (m *ListCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCategoryResponse.Merge(m, src)
}
func (m *ListCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_ListCategoryResponse.Size(m)
}
func (m *ListCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCategoryResponse proto.InternalMessageInfo

func (m *ListCategoryResponse) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type AddItemRequest struct {
	CategoryId           string   `protobuf:"bytes,1,opt,name=category_id,proto3" json:"category_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddItemRequest) Reset()         { *m = AddItemRequest{} }
func (m *AddItemRequest) String() string { return proto.CompactTextString(m) }
func (*AddItemRequest) ProtoMessage()    {}
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{19}
}

func (m *AddItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddItemRequest.Unmarshal(m, b)
}
func (m *AddItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddItemRequest.Marshal(b, m, deterministic)
}
func (m *AddItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddItemRequest.Merge(m, src)
}
func (m *AddItemRequest) XXX_Size() int {
	return xxx_messageInfo_AddItemRequest.Size(m)
}
func (m *AddItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddItemRequest proto.InternalMessageInfo

func (m *AddItemRequest) GetCategoryId() string {
	if m != nil {
		return m.CategoryId
	}
	return ""
}

func (m *AddItemRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddItemResponse struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddItemResponse) Reset()         { *m = AddItemResponse{} }
func (m *AddItemResponse) String() string { return proto.CompactTextString(m) }
func (*AddItemResponse) ProtoMessage()    {}
func (*AddItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{20}
}

func (m *AddItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddItemResponse.Unmarshal(m, b)
}
func (m *AddItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddItemResponse.Marshal(b, m, deterministic)
}
func (m *AddItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddItemResponse.Merge(m, src)
}
func (m *AddItemResponse) XXX_Size() int {
	return xxx_messageInfo_AddItemResponse.Size(m)
}
func (m *AddItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddItemResponse proto.InternalMessageInfo

func (m *AddItemResponse) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type UpdateItemRequest struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateItemRequest) Reset()         { *m = UpdateItemRequest{} }
func (m *UpdateItemRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateItemRequest) ProtoMessage()    {}
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{21}
}

func (m *UpdateItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateItemRequest.Unmarshal(m, b)
}
func (m *UpdateItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateItemRequest.Marshal(b, m, deterministic)
}
func (m *UpdateItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateItemRequest.Merge(m, src)
}
func (m *UpdateItemRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateItemRequest.Size(m)
}
func (m *UpdateItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateItemRequest proto.InternalMessageInfo

func (m *UpdateItemRequest) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type UpdateItemResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateItemResponse) Reset()         { *m = UpdateItemResponse{} }
func (m *UpdateItemResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateItemResponse) ProtoMessage()    {}
func (*UpdateItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{22}
}

func (m *UpdateItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateItemResponse.Unmarshal(m, b)
}
func (m *UpdateItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateItemResponse.Marshal(b, m, deterministic)
}
func (m *UpdateItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateItemResponse.Merge(m, src)
}
func (m *UpdateItemResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateItemResponse.Size(m)
}
func (m *UpdateItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateItemResponse proto.InternalMessageInfo

type DeleteItemRequest struct {
	ItemId               string   `protobuf:"bytes,1,opt,name=item_id,proto3" json:"item_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteItemRequest) Reset()         { *m = DeleteItemRequest{} }
func (m *DeleteItemRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteItemRequest) ProtoMessage()    {}
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{23}
}

func (m *DeleteItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteItemRequest.Unmarshal(m, b)
}
func (m *DeleteItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteItemRequest.Marshal(b, m, deterministic)
}
func (m *DeleteItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteItemRequest.Merge(m, src)
}
func (m *DeleteItemRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteItemRequest.Size(m)
}
func (m *DeleteItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteItemRequest proto.InternalMessageInfo

func (m *DeleteItemRequest) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

type DeleteItemResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteItemResponse) Reset()         { *m = DeleteItemResponse{} }
func (m *DeleteItemResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteItemResponse) ProtoMessage()    {}
func (*DeleteItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{24}
}

func (m *DeleteItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteItemResponse.Unmarshal(m, b)
}
func (m *DeleteItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteItemResponse.Marshal(b, m, deterministic)
}
func (m *DeleteItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteItemResponse.Merge(m, src)
}
func (m *DeleteItemResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteItemResponse.Size(m)
}
func (m *DeleteItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteItemResponse proto.InternalMessageInfo

type ListItemRequest struct {
	CategoryId           string   `protobuf:"bytes,1,opt,name=category_id,proto3" json:"category_id,omitempty"`
	ItemIds              []string `protobuf:"bytes,2,rep,name=item_ids,proto3" json:"item_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListItemRequest) Reset()         { *m = ListItemRequest{} }
func (m *ListItemRequest) String() string { return proto.CompactTextString(m) }
func (*ListItemRequest) ProtoMessage()    {}
func (*ListItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{25}
}

func (m *ListItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListItemRequest.Unmarshal(m, b)
}
func (m *ListItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListItemRequest.Marshal(b, m, deterministic)
}
func (m *ListItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListItemRequest.Merge(m, src)
}
func (m *ListItemRequest) XXX_Size() int {
	return xxx_messageInfo_ListItemRequest.Size(m)
}
func (m *ListItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListItemRequest proto.InternalMessageInfo

func (m *ListItemRequest) GetCategoryId() string {
	if m != nil {
		return m.CategoryId
	}
	return ""
}

func (m *ListItemRequest) GetItemIds() []string {
	if m != nil {
		return m.ItemIds
	}
	return nil
}

type ListItemResponse struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListItemResponse) Reset()         { *m = ListItemResponse{} }
func (m *ListItemResponse) String() string { return proto.CompactTextString(m) }
func (*ListItemResponse) ProtoMessage()    {}
func (*ListItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0357f39af0c26546, []int{26}
}

func (m *ListItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListItemResponse.Unmarshal(m, b)
}
func (m *ListItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListItemResponse.Marshal(b, m, deterministic)
}
func (m *ListItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListItemResponse.Merge(m, src)
}
func (m *ListItemResponse) XXX_Size() int {
	return xxx_messageInfo_ListItemResponse.Size(m)
}
func (m *ListItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListItemResponse proto.InternalMessageInfo

func (m *ListItemResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Menu)(nil), "Menu")
	proto.RegisterType((*Category)(nil), "Category")
	proto.RegisterType((*Item)(nil), "Item")
	proto.RegisterType((*CreateMenuRequest)(nil), "CreateMenuRequest")
	proto.RegisterType((*CreateMenuResponse)(nil), "CreateMenuResponse")
	proto.RegisterType((*UpdateMenuRequest)(nil), "UpdateMenuRequest")
	proto.RegisterType((*UpdateMenuResponse)(nil), "UpdateMenuResponse")
	proto.RegisterType((*DeleteMenuRequest)(nil), "DeleteMenuRequest")
	proto.RegisterType((*DeleteMenuResponse)(nil), "DeleteMenuResponse")
	proto.RegisterType((*GetMenuRequest)(nil), "GetMenuRequest")
	proto.RegisterType((*GetMenuResponse)(nil), "GetMenuResponse")
	proto.RegisterType((*AddCategoryRequest)(nil), "AddCategoryRequest")
	proto.RegisterType((*AddCategoryResponse)(nil), "AddCategoryResponse")
	proto.RegisterType((*UpdateCategoryRequest)(nil), "UpdateCategoryRequest")
	proto.RegisterType((*UpdateCategoryResponse)(nil), "UpdateCategoryResponse")
	proto.RegisterType((*DeleteCategoryRequest)(nil), "DeleteCategoryRequest")
	proto.RegisterType((*DeleteCategoryResponse)(nil), "DeleteCategoryResponse")
	proto.RegisterType((*ListCategoryRequest)(nil), "ListCategoryRequest")
	proto.RegisterType((*ListCategoryResponse)(nil), "ListCategoryResponse")
	proto.RegisterType((*AddItemRequest)(nil), "AddItemRequest")
	proto.RegisterType((*AddItemResponse)(nil), "AddItemResponse")
	proto.RegisterType((*UpdateItemRequest)(nil), "UpdateItemRequest")
	proto.RegisterType((*UpdateItemResponse)(nil), "UpdateItemResponse")
	proto.RegisterType((*DeleteItemRequest)(nil), "DeleteItemRequest")
	proto.RegisterType((*DeleteItemResponse)(nil), "DeleteItemResponse")
	proto.RegisterType((*ListItemRequest)(nil), "ListItemRequest")
	proto.RegisterType((*ListItemResponse)(nil), "ListItemResponse")
}

func init() { proto.RegisterFile("menu.proto", fileDescriptor_0357f39af0c26546) }

var fileDescriptor_0357f39af0c26546 = []byte{
	// 553 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x5d, 0x6b, 0x1a, 0x41,
	0x14, 0x65, 0xd5, 0x8d, 0x7a, 0x04, 0xad, 0x1b, 0xd3, 0x6e, 0xda, 0x50, 0x64, 0xa0, 0x90, 0x42,
	0xaa, 0xd0, 0x3e, 0x15, 0xfa, 0x62, 0xd2, 0x4f, 0x68, 0x28, 0x08, 0x7d, 0xe9, 0x8b, 0x6c, 0x9d,
	0x4b, 0x18, 0x88, 0xab, 0xdd, 0x9d, 0x7d, 0xc8, 0x3f, 0xe8, 0x6f, 0xe9, 0xcf, 0xea, 0x2f, 0x29,
	0x33, 0x3b, 0xbb, 0x33, 0xae, 0xb1, 0x9a, 0xe4, 0x6d, 0xe7, 0x9e, 0xd9, 0x73, 0xcf, 0x3d, 0x7b,
	0xae, 0x02, 0x0b, 0x8a, 0xb3, 0xd1, 0x2a, 0x59, 0xca, 0x25, 0xfb, 0xed, 0xa1, 0x71, 0x49, 0x71,
	0x16, 0x74, 0x51, 0x13, 0x3c, 0xf4, 0x86, 0xde, 0x69, 0x7b, 0x5a, 0x13, 0x3c, 0x38, 0x41, 0x9b,
	0x62, 0x29, 0xe4, 0xcd, 0x4c, 0xf0, 0xb0, 0xa6, 0xcb, 0xb6, 0x10, 0x04, 0x68, 0xc4, 0xd1, 0x82,
	0xc2, 0xba, 0x06, 0xf4, 0x73, 0xf0, 0x1c, 0x98, 0x27, 0x14, 0x49, 0xe2, 0xb3, 0x48, 0x86, 0x0d,
	0x8d, 0x38, 0x15, 0x85, 0x67, 0x2b, 0x5e, 0xe0, 0x7e, 0x8e, 0xdb, 0x0a, 0xfb, 0xe3, 0xa1, 0x75,
	0x11, 0x49, 0xba, 0x5a, 0x26, 0x37, 0x1b, 0x72, 0x42, 0x34, 0x95, 0x6a, 0x2b, 0xa6, 0x38, 0xde,
	0x2a, 0x65, 0x88, 0x0e, 0xa7, 0x74, 0x9e, 0x88, 0x95, 0x14, 0xcb, 0xd8, 0x68, 0x71, 0x4b, 0x15,
	0xb1, 0xfe, 0x0e, 0xb1, 0x07, 0x1b, 0x62, 0xff, 0x7a, 0x68, 0x7c, 0x91, 0xb4, 0xd8, 0x10, 0x3a,
	0x44, 0x67, 0x6e, 0x86, 0xb0, 0x62, 0xdd, 0xd2, 0x3d, 0x05, 0x9f, 0xa0, 0x2d, 0x16, 0xd1, 0x15,
	0xcd, 0xb2, 0xe4, 0xda, 0xe8, 0xb5, 0x85, 0x60, 0x00, 0x7f, 0x95, 0x88, 0x39, 0x69, 0xa5, 0xfe,
	0x34, 0x3f, 0x54, 0x86, 0x6c, 0xee, 0x18, 0xb2, 0xb5, 0x31, 0xe4, 0x07, 0xf4, 0x2f, 0xf4, 0x6d,
	0x95, 0x90, 0x29, 0xfd, 0xca, 0x28, 0x95, 0xeb, 0xc1, 0xf0, 0xb6, 0x05, 0xa3, 0x66, 0x87, 0x63,
	0x63, 0x04, 0x2e, 0x4d, 0xba, 0x5a, 0xc6, 0x29, 0x05, 0xc7, 0x68, 0xa8, 0x4f, 0xa8, 0x29, 0x3a,
	0xaf, 0xfd, 0x91, 0x06, 0x75, 0x89, 0x4d, 0xd0, 0xff, 0xae, 0x55, 0xb8, 0x7d, 0x9d, 0x04, 0x78,
	0xb7, 0x27, 0xc0, 0xed, 0x39, 0x40, 0xe0, 0x52, 0xe4, 0x3d, 0xd9, 0x2b, 0xf4, 0xdf, 0xd3, 0x35,
	0xed, 0x49, 0xac, 0x48, 0xdc, 0xeb, 0x86, 0xe4, 0x33, 0xba, 0x9f, 0x48, 0xee, 0x6f, 0xc9, 0xd6,
	0xe8, 0xb2, 0x33, 0xf4, 0x4a, 0xa6, 0xdd, 0xae, 0x9c, 0x23, 0x98, 0x70, 0x5e, 0x6c, 0xc8, 0xfd,
	0x6c, 0x79, 0x87, 0xc3, 0x35, 0x0e, 0xd3, 0xf5, 0x05, 0x5a, 0x45, 0x42, 0x4d, 0xe7, 0xf6, 0xa8,
	0xbc, 0x54, 0x42, 0xec, 0x12, 0x47, 0xb9, 0xa9, 0x55, 0x11, 0x95, 0xd0, 0x7b, 0xdb, 0x43, 0xef,
	0x8a, 0x09, 0xf1, 0xb8, 0x4a, 0x67, 0x2c, 0x7e, 0x8b, 0xa3, 0xdc, 0xf8, 0x3b, 0x37, 0x52, 0xa4,
	0xd5, 0x57, 0x0d, 0xe9, 0x18, 0x87, 0x5f, 0x45, 0x2a, 0xf7, 0x36, 0x90, 0x4d, 0x30, 0x58, 0x7f,
	0xc1, 0xb8, 0xf5, 0x12, 0x30, 0x1d, 0x05, 0xa5, 0xa1, 0x37, 0xac, 0xaf, 0xfb, 0xe5, 0x80, 0xec,
	0x23, 0xba, 0x13, 0xce, 0xd5, 0x0f, 0xc5, 0xc3, 0xac, 0x3a, 0x43, 0xaf, 0xe4, 0xb1, 0x49, 0x11,
	0x92, 0x16, 0x65, 0x52, 0x34, 0xa8, 0x4b, 0x6c, 0x54, 0xec, 0x8f, 0xdb, 0xf8, 0x3f, 0xf7, 0xcb,
	0x65, 0x71, 0x1b, 0xd8, 0x65, 0x71, 0x59, 0x42, 0x34, 0xd5, 0x2b, 0x8e, 0x5b, 0xe6, 0x68, 0x97,
	0x65, 0x8d, 0xe4, 0x1b, 0x7a, 0xca, 0xc3, 0xbb, 0x39, 0xf0, 0x14, 0x2d, 0xc3, 0x9a, 0x86, 0xb5,
	0x61, 0xfd, 0xb4, 0x3d, 0x2d, 0xcf, 0x6c, 0x8c, 0x47, 0x96, 0xd0, 0x58, 0xf1, 0x0c, 0xbe, 0xc2,
	0x8b, 0x6f, 0x61, 0x66, 0xcb, 0x6b, 0xe7, 0xc7, 0x3f, 0x9e, 0x8c, 0xc6, 0x09, 0xa5, 0x32, 0xca,
	0x92, 0x28, 0x96, 0x33, 0xfb, 0xf8, 0xf3, 0x40, 0xff, 0x07, 0xbe, 0xf9, 0x17, 0x00, 0x00, 0xff,
	0xff, 0x7c, 0x31, 0xba, 0xcb, 0x11, 0x07, 0x00, 0x00,
}
