// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package restaurant_restaurant

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderItem struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity             int32    `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price                int32    `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	TotalPrice           int32    `protobuf:"varint,5,opt,name=total_price,proto3" json:"total_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderItem) Reset()         { *m = OrderItem{} }
func (m *OrderItem) String() string { return proto.CompactTextString(m) }
func (*OrderItem) ProtoMessage()    {}
func (*OrderItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *OrderItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderItem.Unmarshal(m, b)
}
func (m *OrderItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderItem.Marshal(b, m, deterministic)
}
func (m *OrderItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderItem.Merge(m, src)
}
func (m *OrderItem) XXX_Size() int {
	return xxx_messageInfo_OrderItem.Size(m)
}
func (m *OrderItem) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderItem.DiscardUnknown(m)
}

var xxx_messageInfo_OrderItem proto.InternalMessageInfo

func (m *OrderItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrderItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OrderItem) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *OrderItem) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderItem) GetTotalPrice() int32 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

type Order struct {
	Id                   string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RestaurantId         string              `protobuf:"bytes,2,opt,name=restaurant_id,proto3" json:"restaurant_id,omitempty"`
	Status               string              `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Eater                *Order_EaterInfo    `protobuf:"bytes,4,opt,name=eater,proto3" json:"eater,omitempty"`
	Delivery             *Order_DeliveryInfo `protobuf:"bytes,5,opt,name=delivery,proto3" json:"delivery,omitempty"`
	Payment              *Order_PaymentInfo  `protobuf:"bytes,6,opt,name=payment,proto3" json:"payment,omitempty"`
	Items                []*OrderItem        `protobuf:"bytes,7,rep,name=items,proto3" json:"items,omitempty"`
	CreatedAt            string              `protobuf:"bytes,8,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt            string              `protobuf:"bytes,9,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetRestaurantId() string {
	if m != nil {
		return m.RestaurantId
	}
	return ""
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Order) GetEater() *Order_EaterInfo {
	if m != nil {
		return m.Eater
	}
	return nil
}

func (m *Order) GetDelivery() *Order_DeliveryInfo {
	if m != nil {
		return m.Delivery
	}
	return nil
}

func (m *Order) GetPayment() *Order_PaymentInfo {
	if m != nil {
		return m.Payment
	}
	return nil
}

func (m *Order) GetItems() []*OrderItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Order) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Order) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type Order_EaterInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order_EaterInfo) Reset()         { *m = Order_EaterInfo{} }
func (m *Order_EaterInfo) String() string { return proto.CompactTextString(m) }
func (*Order_EaterInfo) ProtoMessage()    {}
func (*Order_EaterInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1, 0}
}

func (m *Order_EaterInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order_EaterInfo.Unmarshal(m, b)
}
func (m *Order_EaterInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order_EaterInfo.Marshal(b, m, deterministic)
}
func (m *Order_EaterInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order_EaterInfo.Merge(m, src)
}
func (m *Order_EaterInfo) XXX_Size() int {
	return xxx_messageInfo_Order_EaterInfo.Size(m)
}
func (m *Order_EaterInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Order_EaterInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Order_EaterInfo proto.InternalMessageInfo

func (m *Order_EaterInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order_EaterInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Order_DeliveryInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             float64  `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order_DeliveryInfo) Reset()         { *m = Order_DeliveryInfo{} }
func (m *Order_DeliveryInfo) String() string { return proto.CompactTextString(m) }
func (*Order_DeliveryInfo) ProtoMessage()    {}
func (*Order_DeliveryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1, 1}
}

func (m *Order_DeliveryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order_DeliveryInfo.Unmarshal(m, b)
}
func (m *Order_DeliveryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order_DeliveryInfo.Marshal(b, m, deterministic)
}
func (m *Order_DeliveryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order_DeliveryInfo.Merge(m, src)
}
func (m *Order_DeliveryInfo) XXX_Size() int {
	return xxx_messageInfo_Order_DeliveryInfo.Size(m)
}
func (m *Order_DeliveryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Order_DeliveryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Order_DeliveryInfo proto.InternalMessageInfo

func (m *Order_DeliveryInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Order_DeliveryInfo) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Order_DeliveryInfo) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

type Order_PaymentInfo struct {
	Method               string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	DeliveryPrice        int32    `protobuf:"varint,2,opt,name=delivery_price,proto3" json:"delivery_price,omitempty"`
	TotalPrice           int32    `protobuf:"varint,3,opt,name=total_price,proto3" json:"total_price,omitempty"`
	CardId               string   `protobuf:"bytes,4,opt,name=card_id,proto3" json:"card_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order_PaymentInfo) Reset()         { *m = Order_PaymentInfo{} }
func (m *Order_PaymentInfo) String() string { return proto.CompactTextString(m) }
func (*Order_PaymentInfo) ProtoMessage()    {}
func (*Order_PaymentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1, 2}
}

func (m *Order_PaymentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order_PaymentInfo.Unmarshal(m, b)
}
func (m *Order_PaymentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order_PaymentInfo.Marshal(b, m, deterministic)
}
func (m *Order_PaymentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order_PaymentInfo.Merge(m, src)
}
func (m *Order_PaymentInfo) XXX_Size() int {
	return xxx_messageInfo_Order_PaymentInfo.Size(m)
}
func (m *Order_PaymentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Order_PaymentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Order_PaymentInfo proto.InternalMessageInfo

func (m *Order_PaymentInfo) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Order_PaymentInfo) GetDeliveryPrice() int32 {
	if m != nil {
		return m.DeliveryPrice
	}
	return 0
}

func (m *Order_PaymentInfo) GetTotalPrice() int32 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

func (m *Order_PaymentInfo) GetCardId() string {
	if m != nil {
		return m.CardId
	}
	return ""
}

type UpdateOrderRequest struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateOrderRequest) Reset()         { *m = UpdateOrderRequest{} }
func (m *UpdateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateOrderRequest) ProtoMessage()    {}
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *UpdateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOrderRequest.Unmarshal(m, b)
}
func (m *UpdateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOrderRequest.Marshal(b, m, deterministic)
}
func (m *UpdateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOrderRequest.Merge(m, src)
}
func (m *UpdateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateOrderRequest.Size(m)
}
func (m *UpdateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOrderRequest proto.InternalMessageInfo

func (m *UpdateOrderRequest) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type UpdateOrderResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateOrderResponse) Reset()         { *m = UpdateOrderResponse{} }
func (m *UpdateOrderResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateOrderResponse) ProtoMessage()    {}
func (*UpdateOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{3}
}

func (m *UpdateOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOrderResponse.Unmarshal(m, b)
}
func (m *UpdateOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOrderResponse.Marshal(b, m, deterministic)
}
func (m *UpdateOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOrderResponse.Merge(m, src)
}
func (m *UpdateOrderResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateOrderResponse.Size(m)
}
func (m *UpdateOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOrderResponse proto.InternalMessageInfo

func (m *UpdateOrderResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type DeleteOrderRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOrderRequest) Reset()         { *m = DeleteOrderRequest{} }
func (m *DeleteOrderRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteOrderRequest) ProtoMessage()    {}
func (*DeleteOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{4}
}

func (m *DeleteOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOrderRequest.Unmarshal(m, b)
}
func (m *DeleteOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOrderRequest.Marshal(b, m, deterministic)
}
func (m *DeleteOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOrderRequest.Merge(m, src)
}
func (m *DeleteOrderRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteOrderRequest.Size(m)
}
func (m *DeleteOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOrderRequest proto.InternalMessageInfo

func (m *DeleteOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type DeleteOrderResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOrderResponse) Reset()         { *m = DeleteOrderResponse{} }
func (m *DeleteOrderResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteOrderResponse) ProtoMessage()    {}
func (*DeleteOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{5}
}

func (m *DeleteOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOrderResponse.Unmarshal(m, b)
}
func (m *DeleteOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOrderResponse.Marshal(b, m, deterministic)
}
func (m *DeleteOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOrderResponse.Merge(m, src)
}
func (m *DeleteOrderResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteOrderResponse.Size(m)
}
func (m *DeleteOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOrderResponse proto.InternalMessageInfo

type GetOrderRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderRequest) Reset()         { *m = GetOrderRequest{} }
func (m *GetOrderRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrderRequest) ProtoMessage()    {}
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{6}
}

func (m *GetOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderRequest.Unmarshal(m, b)
}
func (m *GetOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderRequest.Marshal(b, m, deterministic)
}
func (m *GetOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderRequest.Merge(m, src)
}
func (m *GetOrderRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrderRequest.Size(m)
}
func (m *GetOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderRequest proto.InternalMessageInfo

func (m *GetOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type GetOrderResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderResponse) Reset()         { *m = GetOrderResponse{} }
func (m *GetOrderResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrderResponse) ProtoMessage()    {}
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{7}
}

func (m *GetOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderResponse.Unmarshal(m, b)
}
func (m *GetOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderResponse.Marshal(b, m, deterministic)
}
func (m *GetOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderResponse.Merge(m, src)
}
func (m *GetOrderResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrderResponse.Size(m)
}
func (m *GetOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderResponse proto.InternalMessageInfo

func (m *GetOrderResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type ConfirmOrderRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmOrderRequest) Reset()         { *m = ConfirmOrderRequest{} }
func (m *ConfirmOrderRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmOrderRequest) ProtoMessage()    {}
func (*ConfirmOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{8}
}

func (m *ConfirmOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmOrderRequest.Unmarshal(m, b)
}
func (m *ConfirmOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmOrderRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmOrderRequest.Merge(m, src)
}
func (m *ConfirmOrderRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmOrderRequest.Size(m)
}
func (m *ConfirmOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmOrderRequest proto.InternalMessageInfo

func (m *ConfirmOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type ConfirmOrderResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmOrderResponse) Reset()         { *m = ConfirmOrderResponse{} }
func (m *ConfirmOrderResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmOrderResponse) ProtoMessage()    {}
func (*ConfirmOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{9}
}

func (m *ConfirmOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmOrderResponse.Unmarshal(m, b)
}
func (m *ConfirmOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmOrderResponse.Marshal(b, m, deterministic)
}
func (m *ConfirmOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmOrderResponse.Merge(m, src)
}
func (m *ConfirmOrderResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmOrderResponse.Size(m)
}
func (m *ConfirmOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmOrderResponse proto.InternalMessageInfo

type DeclineOrderRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeclineOrderRequest) Reset()         { *m = DeclineOrderRequest{} }
func (m *DeclineOrderRequest) String() string { return proto.CompactTextString(m) }
func (*DeclineOrderRequest) ProtoMessage()    {}
func (*DeclineOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{10}
}

func (m *DeclineOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeclineOrderRequest.Unmarshal(m, b)
}
func (m *DeclineOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeclineOrderRequest.Marshal(b, m, deterministic)
}
func (m *DeclineOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeclineOrderRequest.Merge(m, src)
}
func (m *DeclineOrderRequest) XXX_Size() int {
	return xxx_messageInfo_DeclineOrderRequest.Size(m)
}
func (m *DeclineOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeclineOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeclineOrderRequest proto.InternalMessageInfo

func (m *DeclineOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type DeclineOrderResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeclineOrderResponse) Reset()         { *m = DeclineOrderResponse{} }
func (m *DeclineOrderResponse) String() string { return proto.CompactTextString(m) }
func (*DeclineOrderResponse) ProtoMessage()    {}
func (*DeclineOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{11}
}

func (m *DeclineOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeclineOrderResponse.Unmarshal(m, b)
}
func (m *DeclineOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeclineOrderResponse.Marshal(b, m, deterministic)
}
func (m *DeclineOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeclineOrderResponse.Merge(m, src)
}
func (m *DeclineOrderResponse) XXX_Size() int {
	return xxx_messageInfo_DeclineOrderResponse.Size(m)
}
func (m *DeclineOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeclineOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeclineOrderResponse proto.InternalMessageInfo

type ListOrderRequest struct {
	RestaurantId         string   `protobuf:"bytes,1,opt,name=restaurant_id,proto3" json:"restaurant_id,omitempty"`
	Sort                 string   `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	Page                 int32    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,4,opt,name=page_size,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOrderRequest) Reset()         { *m = ListOrderRequest{} }
func (m *ListOrderRequest) String() string { return proto.CompactTextString(m) }
func (*ListOrderRequest) ProtoMessage()    {}
func (*ListOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{12}
}

func (m *ListOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrderRequest.Unmarshal(m, b)
}
func (m *ListOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrderRequest.Marshal(b, m, deterministic)
}
func (m *ListOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrderRequest.Merge(m, src)
}
func (m *ListOrderRequest) XXX_Size() int {
	return xxx_messageInfo_ListOrderRequest.Size(m)
}
func (m *ListOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrderRequest proto.InternalMessageInfo

func (m *ListOrderRequest) GetRestaurantId() string {
	if m != nil {
		return m.RestaurantId
	}
	return ""
}

func (m *ListOrderRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *ListOrderRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListOrderRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ListOrderResponse struct {
	Orders               []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOrderResponse) Reset()         { *m = ListOrderResponse{} }
func (m *ListOrderResponse) String() string { return proto.CompactTextString(m) }
func (*ListOrderResponse) ProtoMessage()    {}
func (*ListOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{13}
}

func (m *ListOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrderResponse.Unmarshal(m, b)
}
func (m *ListOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrderResponse.Marshal(b, m, deterministic)
}
func (m *ListOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrderResponse.Merge(m, src)
}
func (m *ListOrderResponse) XXX_Size() int {
	return xxx_messageInfo_ListOrderResponse.Size(m)
}
func (m *ListOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrderResponse proto.InternalMessageInfo

func (m *ListOrderResponse) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func init() {
	proto.RegisterType((*OrderItem)(nil), "OrderItem")
	proto.RegisterType((*Order)(nil), "Order")
	proto.RegisterType((*Order_EaterInfo)(nil), "Order.EaterInfo")
	proto.RegisterType((*Order_DeliveryInfo)(nil), "Order.DeliveryInfo")
	proto.RegisterType((*Order_PaymentInfo)(nil), "Order.PaymentInfo")
	proto.RegisterType((*UpdateOrderRequest)(nil), "UpdateOrderRequest")
	proto.RegisterType((*UpdateOrderResponse)(nil), "UpdateOrderResponse")
	proto.RegisterType((*DeleteOrderRequest)(nil), "DeleteOrderRequest")
	proto.RegisterType((*DeleteOrderResponse)(nil), "DeleteOrderResponse")
	proto.RegisterType((*GetOrderRequest)(nil), "GetOrderRequest")
	proto.RegisterType((*GetOrderResponse)(nil), "GetOrderResponse")
	proto.RegisterType((*ConfirmOrderRequest)(nil), "ConfirmOrderRequest")
	proto.RegisterType((*ConfirmOrderResponse)(nil), "ConfirmOrderResponse")
	proto.RegisterType((*DeclineOrderRequest)(nil), "DeclineOrderRequest")
	proto.RegisterType((*DeclineOrderResponse)(nil), "DeclineOrderResponse")
	proto.RegisterType((*ListOrderRequest)(nil), "ListOrderRequest")
	proto.RegisterType((*ListOrderResponse)(nil), "ListOrderResponse")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 571 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdd, 0x8a, 0xd3, 0x40,
	0x14, 0x26, 0x6d, 0xd3, 0x6d, 0x4e, 0x74, 0xad, 0xd3, 0x75, 0x8d, 0x65, 0x59, 0x4a, 0x90, 0xa5,
	0x17, 0xda, 0xee, 0xb6, 0x6f, 0xa0, 0x2b, 0xb2, 0x20, 0x28, 0x01, 0x6f, 0x44, 0x28, 0x63, 0x33,
	0xbb, 0x0e, 0xe4, 0x6f, 0x67, 0x26, 0x42, 0xbd, 0xf0, 0xc6, 0x2b, 0x1f, 0xd1, 0xb7, 0x91, 0x39,
	0x33, 0x49, 0x93, 0x56, 0xb0, 0x5e, 0x65, 0xce, 0xf7, 0x9d, 0x33, 0xe7, 0x3b, 0x3f, 0x13, 0xf0,
	0x73, 0x11, 0x33, 0x31, 0x2b, 0x44, 0xae, 0xf2, 0xf0, 0xa7, 0x03, 0xde, 0x7b, 0x6d, 0xdf, 0x28,
	0x96, 0x92, 0x63, 0xe8, 0xf0, 0x38, 0x70, 0x26, 0xce, 0xd4, 0x8b, 0x3a, 0x3c, 0x26, 0x04, 0x7a,
	0x19, 0x4d, 0x59, 0xd0, 0x41, 0x04, 0xcf, 0x64, 0x0c, 0x83, 0xfb, 0x92, 0x66, 0x8a, 0xab, 0x4d,
	0xd0, 0x9d, 0x38, 0x53, 0x37, 0xaa, 0x6d, 0x72, 0x02, 0x6e, 0x21, 0xf8, 0x9a, 0x05, 0x3d, 0x24,
	0x8c, 0x41, 0x26, 0xe0, 0xab, 0x5c, 0xd1, 0x64, 0x65, 0x38, 0x17, 0xb9, 0x26, 0x14, 0xfe, 0xee,
	0x81, 0x8b, 0x2a, 0xf6, 0x14, 0x3c, 0x87, 0x87, 0x82, 0x49, 0x45, 0x4b, 0x41, 0x33, 0xb5, 0xe2,
	0xb1, 0x95, 0xd2, 0x06, 0xc9, 0x29, 0xf4, 0xa5, 0xa2, 0xaa, 0x94, 0xa8, 0xc8, 0x8b, 0xac, 0x45,
	0x2e, 0xc0, 0x65, 0x54, 0x31, 0x81, 0x7a, 0xfc, 0xc5, 0x70, 0x86, 0x49, 0x66, 0x6f, 0x34, 0x76,
	0x93, 0xdd, 0xe6, 0x91, 0xa1, 0xc9, 0x1c, 0x06, 0x31, 0x4b, 0xf8, 0x37, 0x26, 0x36, 0x28, 0xcf,
	0x5f, 0x8c, 0xac, 0xeb, 0xb5, 0x85, 0xd1, 0xbb, 0x76, 0x22, 0x2f, 0xe0, 0xa8, 0xa0, 0x9b, 0x94,
	0x65, 0x2a, 0xe8, 0xa3, 0x3f, 0xb1, 0xfe, 0x1f, 0x0c, 0x8a, 0xee, 0x95, 0x0b, 0x99, 0x80, 0xcb,
	0x15, 0x4b, 0x65, 0x70, 0x34, 0xe9, 0x4e, 0xfd, 0x05, 0xcc, 0xea, 0x8e, 0x47, 0x86, 0x20, 0xe7,
	0x00, 0x6b, 0xa1, 0xb5, 0xc4, 0x2b, 0xaa, 0x82, 0x01, 0x16, 0xd1, 0x40, 0x34, 0x5f, 0x16, 0x71,
	0xc5, 0x7b, 0x86, 0xdf, 0x22, 0xe3, 0x39, 0x78, 0x75, 0x51, 0x87, 0x4c, 0x71, 0xfc, 0x19, 0x1e,
	0x34, 0x4b, 0xab, 0x7d, 0x9c, 0xc6, 0xa4, 0xcf, 0xc0, 0x4b, 0xf2, 0xec, 0x8e, 0xab, 0x32, 0x36,
	0xc1, 0x4e, 0xb4, 0x05, 0xf4, 0x1e, 0x24, 0x54, 0x19, 0xb2, 0x8b, 0x64, 0x6d, 0x8f, 0x7f, 0x39,
	0xe0, 0x37, 0x3a, 0xa1, 0xe7, 0x93, 0x32, 0xf5, 0x35, 0xaf, 0x54, 0x59, 0x8b, 0x5c, 0xc0, 0x71,
	0xd5, 0x52, 0xbb, 0x1c, 0x1d, 0x5c, 0x8e, 0x1d, 0x74, 0x77, 0x83, 0xba, 0x7b, 0x1b, 0x44, 0x02,
	0x38, 0x5a, 0x53, 0x11, 0xeb, 0x0d, 0xe9, 0x61, 0x8a, 0xca, 0x0c, 0x17, 0x40, 0x3e, 0x62, 0xa3,
	0xb0, 0xe9, 0x11, 0xbb, 0x2f, 0x99, 0x54, 0xe4, 0x0c, 0x5c, 0x7c, 0x06, 0x28, 0xc8, 0x5f, 0xf4,
	0xcd, 0x48, 0x22, 0x03, 0x86, 0x4b, 0x18, 0xb5, 0x62, 0x64, 0x91, 0x67, 0x92, 0xfd, 0x23, 0xe8,
	0x12, 0xc8, 0x35, 0x4b, 0xd8, 0x4e, 0xa2, 0x31, 0x0c, 0x90, 0x5e, 0xd5, 0x23, 0xa9, 0xed, 0xf0,
	0x09, 0x8c, 0x5a, 0x11, 0x26, 0x4d, 0xf8, 0x12, 0x1e, 0xbd, 0x65, 0xea, 0xe0, 0x5b, 0x2e, 0x61,
	0xb8, 0x75, 0x3f, 0x48, 0xe9, 0x15, 0x8c, 0x5e, 0xe7, 0xd9, 0x2d, 0x17, 0xe9, 0xc1, 0x49, 0x4e,
	0xe1, 0xa4, 0x1d, 0x62, 0xb5, 0x5e, 0xe9, 0x12, 0xd6, 0x09, 0xcf, 0xd8, 0xff, 0x5c, 0xd5, 0x0e,
	0xb1, 0x57, 0xfd, 0x80, 0xe1, 0x3b, 0x2e, 0xdb, 0x75, 0xef, 0x3d, 0x7f, 0xe7, 0x6f, 0xcf, 0x9f,
	0x40, 0x4f, 0xe6, 0x42, 0x55, 0x0b, 0xae, 0xcf, 0x1a, 0x2b, 0xe8, 0x5d, 0xb5, 0x2b, 0x78, 0xd6,
	0x0b, 0xad, 0xbf, 0x2b, 0xc9, 0xbf, 0x57, 0xbf, 0xa8, 0x2d, 0x10, 0x2e, 0xe1, 0x71, 0x23, 0xbf,
	0x6d, 0xe4, 0x39, 0xf4, 0x51, 0xb8, 0x0c, 0x1c, 0x7c, 0xbb, 0x55, 0x27, 0x2d, 0xfa, 0xea, 0xd9,
	0xa7, 0xa7, 0xb3, 0x79, 0x43, 0xcd, 0xf6, 0xf8, 0xa5, 0x8f, 0x7f, 0xd8, 0xe5, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x8c, 0xc1, 0x8d, 0xa2, 0x70, 0x05, 0x00, 0x00,
}
