// Code generated by protoc-gen-go. DO NOT EDIT.
// source: restaurant_entity.proto

package restaurant_restaurant

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RestaurantEntity struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	LogoUrl              string   `protobuf:"bytes,4,opt,name=logo_url,proto3" json:"logo_url,omitempty"`
	ImageUrl             string   `protobuf:"bytes,5,opt,name=image_url,proto3" json:"image_url,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,7,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestaurantEntity) Reset()         { *m = RestaurantEntity{} }
func (m *RestaurantEntity) String() string { return proto.CompactTextString(m) }
func (*RestaurantEntity) ProtoMessage()    {}
func (*RestaurantEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_67d9bf92fe46e21d, []int{0}
}

func (m *RestaurantEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestaurantEntity.Unmarshal(m, b)
}
func (m *RestaurantEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestaurantEntity.Marshal(b, m, deterministic)
}
func (m *RestaurantEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestaurantEntity.Merge(m, src)
}
func (m *RestaurantEntity) XXX_Size() int {
	return xxx_messageInfo_RestaurantEntity.Size(m)
}
func (m *RestaurantEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_RestaurantEntity.DiscardUnknown(m)
}

var xxx_messageInfo_RestaurantEntity proto.InternalMessageInfo

func (m *RestaurantEntity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RestaurantEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RestaurantEntity) GetLogoUrl() string {
	if m != nil {
		return m.LogoUrl
	}
	return ""
}

func (m *RestaurantEntity) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *RestaurantEntity) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *RestaurantEntity) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type CreateRestaurantEntityRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,json=id,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRestaurantEntityRequest) Reset()         { *m = CreateRestaurantEntityRequest{} }
func (m *CreateRestaurantEntityRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRestaurantEntityRequest) ProtoMessage()    {}
func (*CreateRestaurantEntityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67d9bf92fe46e21d, []int{1}
}

func (m *CreateRestaurantEntityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRestaurantEntityRequest.Unmarshal(m, b)
}
func (m *CreateRestaurantEntityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRestaurantEntityRequest.Marshal(b, m, deterministic)
}
func (m *CreateRestaurantEntityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRestaurantEntityRequest.Merge(m, src)
}
func (m *CreateRestaurantEntityRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRestaurantEntityRequest.Size(m)
}
func (m *CreateRestaurantEntityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRestaurantEntityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRestaurantEntityRequest proto.InternalMessageInfo

func (m *CreateRestaurantEntityRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateRestaurantEntityResponse struct {
	Entity               *RestaurantEntity `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateRestaurantEntityResponse) Reset()         { *m = CreateRestaurantEntityResponse{} }
func (m *CreateRestaurantEntityResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRestaurantEntityResponse) ProtoMessage()    {}
func (*CreateRestaurantEntityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_67d9bf92fe46e21d, []int{2}
}

func (m *CreateRestaurantEntityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRestaurantEntityResponse.Unmarshal(m, b)
}
func (m *CreateRestaurantEntityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRestaurantEntityResponse.Marshal(b, m, deterministic)
}
func (m *CreateRestaurantEntityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRestaurantEntityResponse.Merge(m, src)
}
func (m *CreateRestaurantEntityResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRestaurantEntityResponse.Size(m)
}
func (m *CreateRestaurantEntityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRestaurantEntityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRestaurantEntityResponse proto.InternalMessageInfo

func (m *CreateRestaurantEntityResponse) GetEntity() *RestaurantEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type UpdateRestaurantEntityRequest struct {
	Entity               *RestaurantEntity `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateRestaurantEntityRequest) Reset()         { *m = UpdateRestaurantEntityRequest{} }
func (m *UpdateRestaurantEntityRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRestaurantEntityRequest) ProtoMessage()    {}
func (*UpdateRestaurantEntityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67d9bf92fe46e21d, []int{3}
}

func (m *UpdateRestaurantEntityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRestaurantEntityRequest.Unmarshal(m, b)
}
func (m *UpdateRestaurantEntityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRestaurantEntityRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRestaurantEntityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRestaurantEntityRequest.Merge(m, src)
}
func (m *UpdateRestaurantEntityRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRestaurantEntityRequest.Size(m)
}
func (m *UpdateRestaurantEntityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRestaurantEntityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRestaurantEntityRequest proto.InternalMessageInfo

func (m *UpdateRestaurantEntityRequest) GetEntity() *RestaurantEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type UpdateRestaurantEntityResponse struct {
	Entity               *RestaurantEntity `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateRestaurantEntityResponse) Reset()         { *m = UpdateRestaurantEntityResponse{} }
func (m *UpdateRestaurantEntityResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRestaurantEntityResponse) ProtoMessage()    {}
func (*UpdateRestaurantEntityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_67d9bf92fe46e21d, []int{4}
}

func (m *UpdateRestaurantEntityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRestaurantEntityResponse.Unmarshal(m, b)
}
func (m *UpdateRestaurantEntityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRestaurantEntityResponse.Marshal(b, m, deterministic)
}
func (m *UpdateRestaurantEntityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRestaurantEntityResponse.Merge(m, src)
}
func (m *UpdateRestaurantEntityResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRestaurantEntityResponse.Size(m)
}
func (m *UpdateRestaurantEntityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRestaurantEntityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRestaurantEntityResponse proto.InternalMessageInfo

func (m *UpdateRestaurantEntityResponse) GetEntity() *RestaurantEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type ListRestaurantEntityRequest struct {
	Sort                 string   `protobuf:"bytes,1,opt,name=sort,proto3" json:"sort,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=page_size,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRestaurantEntityRequest) Reset()         { *m = ListRestaurantEntityRequest{} }
func (m *ListRestaurantEntityRequest) String() string { return proto.CompactTextString(m) }
func (*ListRestaurantEntityRequest) ProtoMessage()    {}
func (*ListRestaurantEntityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67d9bf92fe46e21d, []int{5}
}

func (m *ListRestaurantEntityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRestaurantEntityRequest.Unmarshal(m, b)
}
func (m *ListRestaurantEntityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRestaurantEntityRequest.Marshal(b, m, deterministic)
}
func (m *ListRestaurantEntityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRestaurantEntityRequest.Merge(m, src)
}
func (m *ListRestaurantEntityRequest) XXX_Size() int {
	return xxx_messageInfo_ListRestaurantEntityRequest.Size(m)
}
func (m *ListRestaurantEntityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRestaurantEntityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRestaurantEntityRequest proto.InternalMessageInfo

func (m *ListRestaurantEntityRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *ListRestaurantEntityRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListRestaurantEntityRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ListRestaurantEntityResponse struct {
	Entities             []*RestaurantEntity `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListRestaurantEntityResponse) Reset()         { *m = ListRestaurantEntityResponse{} }
func (m *ListRestaurantEntityResponse) String() string { return proto.CompactTextString(m) }
func (*ListRestaurantEntityResponse) ProtoMessage()    {}
func (*ListRestaurantEntityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_67d9bf92fe46e21d, []int{6}
}

func (m *ListRestaurantEntityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRestaurantEntityResponse.Unmarshal(m, b)
}
func (m *ListRestaurantEntityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRestaurantEntityResponse.Marshal(b, m, deterministic)
}
func (m *ListRestaurantEntityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRestaurantEntityResponse.Merge(m, src)
}
func (m *ListRestaurantEntityResponse) XXX_Size() int {
	return xxx_messageInfo_ListRestaurantEntityResponse.Size(m)
}
func (m *ListRestaurantEntityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRestaurantEntityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRestaurantEntityResponse proto.InternalMessageInfo

func (m *ListRestaurantEntityResponse) GetEntities() []*RestaurantEntity {
	if m != nil {
		return m.Entities
	}
	return nil
}

type DeleteRestaurantEntityRequest struct {
	EntityId             string   `protobuf:"bytes,1,opt,name=entity_id,proto3" json:"entity_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRestaurantEntityRequest) Reset()         { *m = DeleteRestaurantEntityRequest{} }
func (m *DeleteRestaurantEntityRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRestaurantEntityRequest) ProtoMessage()    {}
func (*DeleteRestaurantEntityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67d9bf92fe46e21d, []int{7}
}

func (m *DeleteRestaurantEntityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRestaurantEntityRequest.Unmarshal(m, b)
}
func (m *DeleteRestaurantEntityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRestaurantEntityRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRestaurantEntityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRestaurantEntityRequest.Merge(m, src)
}
func (m *DeleteRestaurantEntityRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRestaurantEntityRequest.Size(m)
}
func (m *DeleteRestaurantEntityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRestaurantEntityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRestaurantEntityRequest proto.InternalMessageInfo

func (m *DeleteRestaurantEntityRequest) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

type DeleteRestaurantEntityResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRestaurantEntityResponse) Reset()         { *m = DeleteRestaurantEntityResponse{} }
func (m *DeleteRestaurantEntityResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRestaurantEntityResponse) ProtoMessage()    {}
func (*DeleteRestaurantEntityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_67d9bf92fe46e21d, []int{8}
}

func (m *DeleteRestaurantEntityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRestaurantEntityResponse.Unmarshal(m, b)
}
func (m *DeleteRestaurantEntityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRestaurantEntityResponse.Marshal(b, m, deterministic)
}
func (m *DeleteRestaurantEntityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRestaurantEntityResponse.Merge(m, src)
}
func (m *DeleteRestaurantEntityResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRestaurantEntityResponse.Size(m)
}
func (m *DeleteRestaurantEntityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRestaurantEntityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRestaurantEntityResponse proto.InternalMessageInfo

type SearchRestaurantEntitiesByLocationRequest struct {
	Location             []float64 `protobuf:"fixed64,1,rep,packed,name=location,proto3" json:"location,omitempty"`
	Sort                 string    `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	Page                 int32     `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32     `protobuf:"varint,4,opt,name=page_size,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SearchRestaurantEntitiesByLocationRequest) Reset() {
	*m = SearchRestaurantEntitiesByLocationRequest{}
}
func (m *SearchRestaurantEntitiesByLocationRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRestaurantEntitiesByLocationRequest) ProtoMessage()    {}
func (*SearchRestaurantEntitiesByLocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67d9bf92fe46e21d, []int{9}
}

func (m *SearchRestaurantEntitiesByLocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRestaurantEntitiesByLocationRequest.Unmarshal(m, b)
}
func (m *SearchRestaurantEntitiesByLocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRestaurantEntitiesByLocationRequest.Marshal(b, m, deterministic)
}
func (m *SearchRestaurantEntitiesByLocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRestaurantEntitiesByLocationRequest.Merge(m, src)
}
func (m *SearchRestaurantEntitiesByLocationRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRestaurantEntitiesByLocationRequest.Size(m)
}
func (m *SearchRestaurantEntitiesByLocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRestaurantEntitiesByLocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRestaurantEntitiesByLocationRequest proto.InternalMessageInfo

func (m *SearchRestaurantEntitiesByLocationRequest) GetLocation() []float64 {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *SearchRestaurantEntitiesByLocationRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *SearchRestaurantEntitiesByLocationRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchRestaurantEntitiesByLocationRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type SearchRestaurantEntitiesByLocationResponse struct {
	Entities             []*RestaurantEntity `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SearchRestaurantEntitiesByLocationResponse) Reset() {
	*m = SearchRestaurantEntitiesByLocationResponse{}
}
func (m *SearchRestaurantEntitiesByLocationResponse) String() string {
	return proto.CompactTextString(m)
}
func (*SearchRestaurantEntitiesByLocationResponse) ProtoMessage() {}
func (*SearchRestaurantEntitiesByLocationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_67d9bf92fe46e21d, []int{10}
}

func (m *SearchRestaurantEntitiesByLocationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRestaurantEntitiesByLocationResponse.Unmarshal(m, b)
}
func (m *SearchRestaurantEntitiesByLocationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRestaurantEntitiesByLocationResponse.Marshal(b, m, deterministic)
}
func (m *SearchRestaurantEntitiesByLocationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRestaurantEntitiesByLocationResponse.Merge(m, src)
}
func (m *SearchRestaurantEntitiesByLocationResponse) XXX_Size() int {
	return xxx_messageInfo_SearchRestaurantEntitiesByLocationResponse.Size(m)
}
func (m *SearchRestaurantEntitiesByLocationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRestaurantEntitiesByLocationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRestaurantEntitiesByLocationResponse proto.InternalMessageInfo

func (m *SearchRestaurantEntitiesByLocationResponse) GetEntities() []*RestaurantEntity {
	if m != nil {
		return m.Entities
	}
	return nil
}

type SearchClosestRestaurantsRequest struct {
	EntityId             string    `protobuf:"bytes,1,opt,name=entity_id,proto3" json:"entity_id,omitempty"`
	Location             []float64 `protobuf:"fixed64,2,rep,packed,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SearchClosestRestaurantsRequest) Reset()         { *m = SearchClosestRestaurantsRequest{} }
func (m *SearchClosestRestaurantsRequest) String() string { return proto.CompactTextString(m) }
func (*SearchClosestRestaurantsRequest) ProtoMessage()    {}
func (*SearchClosestRestaurantsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67d9bf92fe46e21d, []int{11}
}

func (m *SearchClosestRestaurantsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchClosestRestaurantsRequest.Unmarshal(m, b)
}
func (m *SearchClosestRestaurantsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchClosestRestaurantsRequest.Marshal(b, m, deterministic)
}
func (m *SearchClosestRestaurantsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchClosestRestaurantsRequest.Merge(m, src)
}
func (m *SearchClosestRestaurantsRequest) XXX_Size() int {
	return xxx_messageInfo_SearchClosestRestaurantsRequest.Size(m)
}
func (m *SearchClosestRestaurantsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchClosestRestaurantsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchClosestRestaurantsRequest proto.InternalMessageInfo

func (m *SearchClosestRestaurantsRequest) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

func (m *SearchClosestRestaurantsRequest) GetLocation() []float64 {
	if m != nil {
		return m.Location
	}
	return nil
}

type SearchClosestRestaurantsResponse struct {
	RestaurantIds        []string `protobuf:"bytes,1,rep,name=restaurant_ids,proto3" json:"restaurant_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchClosestRestaurantsResponse) Reset()         { *m = SearchClosestRestaurantsResponse{} }
func (m *SearchClosestRestaurantsResponse) String() string { return proto.CompactTextString(m) }
func (*SearchClosestRestaurantsResponse) ProtoMessage()    {}
func (*SearchClosestRestaurantsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_67d9bf92fe46e21d, []int{12}
}

func (m *SearchClosestRestaurantsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchClosestRestaurantsResponse.Unmarshal(m, b)
}
func (m *SearchClosestRestaurantsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchClosestRestaurantsResponse.Marshal(b, m, deterministic)
}
func (m *SearchClosestRestaurantsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchClosestRestaurantsResponse.Merge(m, src)
}
func (m *SearchClosestRestaurantsResponse) XXX_Size() int {
	return xxx_messageInfo_SearchClosestRestaurantsResponse.Size(m)
}
func (m *SearchClosestRestaurantsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchClosestRestaurantsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchClosestRestaurantsResponse proto.InternalMessageInfo

func (m *SearchClosestRestaurantsResponse) GetRestaurantIds() []string {
	if m != nil {
		return m.RestaurantIds
	}
	return nil
}

func init() {
	proto.RegisterType((*RestaurantEntity)(nil), "RestaurantEntity")
	proto.RegisterType((*CreateRestaurantEntityRequest)(nil), "CreateRestaurantEntityRequest")
	proto.RegisterType((*CreateRestaurantEntityResponse)(nil), "CreateRestaurantEntityResponse")
	proto.RegisterType((*UpdateRestaurantEntityRequest)(nil), "UpdateRestaurantEntityRequest")
	proto.RegisterType((*UpdateRestaurantEntityResponse)(nil), "UpdateRestaurantEntityResponse")
	proto.RegisterType((*ListRestaurantEntityRequest)(nil), "ListRestaurantEntityRequest")
	proto.RegisterType((*ListRestaurantEntityResponse)(nil), "ListRestaurantEntityResponse")
	proto.RegisterType((*DeleteRestaurantEntityRequest)(nil), "DeleteRestaurantEntityRequest")
	proto.RegisterType((*DeleteRestaurantEntityResponse)(nil), "DeleteRestaurantEntityResponse")
	proto.RegisterType((*SearchRestaurantEntitiesByLocationRequest)(nil), "SearchRestaurantEntitiesByLocationRequest")
	proto.RegisterType((*SearchRestaurantEntitiesByLocationResponse)(nil), "SearchRestaurantEntitiesByLocationResponse")
	proto.RegisterType((*SearchClosestRestaurantsRequest)(nil), "SearchClosestRestaurantsRequest")
	proto.RegisterType((*SearchClosestRestaurantsResponse)(nil), "SearchClosestRestaurantsResponse")
}

func init() { proto.RegisterFile("restaurant_entity.proto", fileDescriptor_67d9bf92fe46e21d) }

var fileDescriptor_67d9bf92fe46e21d = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6f, 0xd4, 0x30,
	0x10, 0x55, 0xb2, 0x1f, 0x34, 0x83, 0x54, 0x15, 0x5f, 0x1a, 0x60, 0x37, 0x44, 0x3e, 0xa0, 0x16,
	0x89, 0x45, 0xc0, 0x99, 0x4b, 0x0b, 0x97, 0xb6, 0x5c, 0x82, 0xb8, 0xd0, 0x43, 0x64, 0x92, 0xd1,
	0x62, 0x29, 0x8d, 0x43, 0xec, 0x1c, 0xca, 0x7f, 0xe0, 0xbf, 0xf0, 0x13, 0x51, 0xc6, 0x69, 0x92,
	0x86, 0xb5, 0xd4, 0xe5, 0x94, 0xc9, 0x7b, 0xe3, 0x99, 0x37, 0x6f, 0x2c, 0xc3, 0x71, 0x8d, 0xda,
	0x88, 0xa6, 0x16, 0xa5, 0x49, 0xb1, 0x34, 0xd2, 0xdc, 0x6e, 0xaa, 0x5a, 0x19, 0xc5, 0xff, 0x78,
	0x70, 0x94, 0xf4, 0xdc, 0x27, 0xa2, 0xd8, 0x21, 0xf8, 0x32, 0x0f, 0xbd, 0xd8, 0x3b, 0x09, 0x12,
	0x5f, 0xe6, 0x8c, 0xc1, 0xbc, 0x14, 0x37, 0x18, 0xce, 0x08, 0xa1, 0x98, 0x3d, 0x83, 0x83, 0x42,
	0x6d, 0x55, 0xda, 0xd4, 0x45, 0x38, 0x27, 0xbc, 0xff, 0x67, 0x2b, 0x08, 0xe4, 0x8d, 0xd8, 0x22,
	0x91, 0x0b, 0x22, 0x07, 0x80, 0x45, 0x00, 0x59, 0x8d, 0xc2, 0x60, 0x9e, 0x0a, 0x13, 0x2e, 0x89,
	0x1e, 0x21, 0x2d, 0xdf, 0x54, 0xf9, 0x1d, 0xff, 0xc8, 0xf2, 0x03, 0xc2, 0xdf, 0xc2, 0xfa, 0x9c,
	0xb2, 0xa7, 0xba, 0x13, 0xfc, 0xd9, 0xa0, 0x36, 0xec, 0xa8, 0x93, 0xdb, 0x0f, 0xc0, 0x2f, 0x21,
	0x72, 0x1d, 0xd1, 0x95, 0x2a, 0x35, 0xb2, 0x53, 0x58, 0x5a, 0x5f, 0xe8, 0xd4, 0xe3, 0x77, 0x4f,
	0x36, 0xff, 0xa4, 0x76, 0x09, 0xfc, 0x02, 0xd6, 0x5f, 0x49, 0x8d, 0xab, 0xff, 0x1e, 0xb5, 0x2e,
	0x21, 0x72, 0xd5, 0xda, 0x5f, 0x58, 0x06, 0xcf, 0xaf, 0xa4, 0x36, 0x2e, 0x59, 0x0c, 0xe6, 0x5a,
	0xd5, 0xa6, 0xb3, 0x85, 0xe2, 0x16, 0xab, 0xc4, 0x16, 0x43, 0x3f, 0xf6, 0x4e, 0x16, 0x09, 0xc5,
	0xed, 0xf6, 0xda, 0x6f, 0xaa, 0xe5, 0x2f, 0xbb, 0xf2, 0x45, 0x32, 0x00, 0xfc, 0x33, 0xac, 0x76,
	0x37, 0xe9, 0xf4, 0xbe, 0x86, 0x03, 0x92, 0x23, 0x51, 0x87, 0x5e, 0x3c, 0xdb, 0xad, 0xb8, 0x4f,
	0xe1, 0x1f, 0x60, 0xfd, 0x11, 0x0b, 0x74, 0x9b, 0xb9, 0x82, 0xc0, 0x8e, 0x97, 0xf6, 0x57, 0x72,
	0x00, 0x78, 0x0c, 0x91, 0xeb, 0xb8, 0xd5, 0xc3, 0x7f, 0x7b, 0x70, 0xfa, 0x05, 0x45, 0x9d, 0xfd,
	0x98, 0xa4, 0x48, 0xd4, 0x67, 0xb7, 0x57, 0x2a, 0x13, 0x46, 0xaa, 0xf2, 0xae, 0x1b, 0xdd, 0x6a,
	0x0b, 0x91, 0x7a, 0x2f, 0xe9, 0xff, 0x7b, 0xff, 0xfc, 0x1d, 0xfe, 0xcd, 0x5c, 0xfe, 0xcd, 0xa7,
	0xfe, 0x5d, 0xc3, 0xab, 0x87, 0xc8, 0xf9, 0x3f, 0x37, 0xaf, 0xe1, 0x85, 0x2d, 0x7e, 0x5e, 0x28,
	0x8d, 0xe3, 0x2d, 0xe9, 0x07, 0xf9, 0x79, 0x6f, 0x7e, 0xff, 0xfe, 0xfc, 0xfc, 0x02, 0x62, 0x77,
	0xf1, 0x4e, 0xef, 0x4b, 0x38, 0x1c, 0xbd, 0x34, 0x32, 0xb7, 0xaa, 0x83, 0x64, 0x82, 0x9e, 0x3d,
	0xfd, 0x76, 0xbc, 0x79, 0x33, 0xc2, 0x86, 0xf0, 0xfb, 0x92, 0x1e, 0xa6, 0xf7, 0x7f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xed, 0x20, 0xd7, 0x88, 0xb3, 0x04, 0x00, 0x00,
}
