// Code generated by protoc-gen-go. DO NOT EDIT.
// source: restaurant.proto

package restaurant_restaurant

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Address struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Longitude            float64  `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             float64  `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_9528536a6390faa1, []int{0}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Address) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Address) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Address) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

type Restaurant struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EntityId             string   `protobuf:"bytes,2,opt,name=entity_id,proto3" json:"entity_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Address              *Address `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Type                 string   `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	CreatedAt            string   `protobuf:"bytes,7,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,8,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Restaurant) Reset()         { *m = Restaurant{} }
func (m *Restaurant) String() string { return proto.CompactTextString(m) }
func (*Restaurant) ProtoMessage()    {}
func (*Restaurant) Descriptor() ([]byte, []int) {
	return fileDescriptor_9528536a6390faa1, []int{1}
}

func (m *Restaurant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Restaurant.Unmarshal(m, b)
}
func (m *Restaurant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Restaurant.Marshal(b, m, deterministic)
}
func (m *Restaurant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Restaurant.Merge(m, src)
}
func (m *Restaurant) XXX_Size() int {
	return xxx_messageInfo_Restaurant.Size(m)
}
func (m *Restaurant) XXX_DiscardUnknown() {
	xxx_messageInfo_Restaurant.DiscardUnknown(m)
}

var xxx_messageInfo_Restaurant proto.InternalMessageInfo

func (m *Restaurant) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Restaurant) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

func (m *Restaurant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Restaurant) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Restaurant) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Restaurant) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Restaurant) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Restaurant) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type AddRestaurantRequest struct {
	EntityId             string   `protobuf:"bytes,1,opt,name=entity_id,proto3" json:"entity_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRestaurantRequest) Reset()         { *m = AddRestaurantRequest{} }
func (m *AddRestaurantRequest) String() string { return proto.CompactTextString(m) }
func (*AddRestaurantRequest) ProtoMessage()    {}
func (*AddRestaurantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9528536a6390faa1, []int{2}
}

func (m *AddRestaurantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRestaurantRequest.Unmarshal(m, b)
}
func (m *AddRestaurantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRestaurantRequest.Marshal(b, m, deterministic)
}
func (m *AddRestaurantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRestaurantRequest.Merge(m, src)
}
func (m *AddRestaurantRequest) XXX_Size() int {
	return xxx_messageInfo_AddRestaurantRequest.Size(m)
}
func (m *AddRestaurantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRestaurantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRestaurantRequest proto.InternalMessageInfo

func (m *AddRestaurantRequest) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

func (m *AddRestaurantRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddRestaurantResponse struct {
	Restaurant           *Restaurant `protobuf:"bytes,1,opt,name=restaurant,proto3" json:"restaurant,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddRestaurantResponse) Reset()         { *m = AddRestaurantResponse{} }
func (m *AddRestaurantResponse) String() string { return proto.CompactTextString(m) }
func (*AddRestaurantResponse) ProtoMessage()    {}
func (*AddRestaurantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9528536a6390faa1, []int{3}
}

func (m *AddRestaurantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRestaurantResponse.Unmarshal(m, b)
}
func (m *AddRestaurantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRestaurantResponse.Marshal(b, m, deterministic)
}
func (m *AddRestaurantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRestaurantResponse.Merge(m, src)
}
func (m *AddRestaurantResponse) XXX_Size() int {
	return xxx_messageInfo_AddRestaurantResponse.Size(m)
}
func (m *AddRestaurantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRestaurantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddRestaurantResponse proto.InternalMessageInfo

func (m *AddRestaurantResponse) GetRestaurant() *Restaurant {
	if m != nil {
		return m.Restaurant
	}
	return nil
}

type UpdateRestaurantRequest struct {
	Restaurant           *Restaurant `protobuf:"bytes,1,opt,name=restaurant,proto3" json:"restaurant,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateRestaurantRequest) Reset()         { *m = UpdateRestaurantRequest{} }
func (m *UpdateRestaurantRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRestaurantRequest) ProtoMessage()    {}
func (*UpdateRestaurantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9528536a6390faa1, []int{4}
}

func (m *UpdateRestaurantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRestaurantRequest.Unmarshal(m, b)
}
func (m *UpdateRestaurantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRestaurantRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRestaurantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRestaurantRequest.Merge(m, src)
}
func (m *UpdateRestaurantRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRestaurantRequest.Size(m)
}
func (m *UpdateRestaurantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRestaurantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRestaurantRequest proto.InternalMessageInfo

func (m *UpdateRestaurantRequest) GetRestaurant() *Restaurant {
	if m != nil {
		return m.Restaurant
	}
	return nil
}

type UpdateRestaurantResponse struct {
	Restaurant           *Restaurant `protobuf:"bytes,1,opt,name=restaurant,proto3" json:"restaurant,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateRestaurantResponse) Reset()         { *m = UpdateRestaurantResponse{} }
func (m *UpdateRestaurantResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRestaurantResponse) ProtoMessage()    {}
func (*UpdateRestaurantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9528536a6390faa1, []int{5}
}

func (m *UpdateRestaurantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRestaurantResponse.Unmarshal(m, b)
}
func (m *UpdateRestaurantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRestaurantResponse.Marshal(b, m, deterministic)
}
func (m *UpdateRestaurantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRestaurantResponse.Merge(m, src)
}
func (m *UpdateRestaurantResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRestaurantResponse.Size(m)
}
func (m *UpdateRestaurantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRestaurantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRestaurantResponse proto.InternalMessageInfo

func (m *UpdateRestaurantResponse) GetRestaurant() *Restaurant {
	if m != nil {
		return m.Restaurant
	}
	return nil
}

type ListRestaurantByEntityRequest struct {
	EntityId             string   `protobuf:"bytes,1,opt,name=entity_id,proto3" json:"entity_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRestaurantByEntityRequest) Reset()         { *m = ListRestaurantByEntityRequest{} }
func (m *ListRestaurantByEntityRequest) String() string { return proto.CompactTextString(m) }
func (*ListRestaurantByEntityRequest) ProtoMessage()    {}
func (*ListRestaurantByEntityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9528536a6390faa1, []int{6}
}

func (m *ListRestaurantByEntityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRestaurantByEntityRequest.Unmarshal(m, b)
}
func (m *ListRestaurantByEntityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRestaurantByEntityRequest.Marshal(b, m, deterministic)
}
func (m *ListRestaurantByEntityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRestaurantByEntityRequest.Merge(m, src)
}
func (m *ListRestaurantByEntityRequest) XXX_Size() int {
	return xxx_messageInfo_ListRestaurantByEntityRequest.Size(m)
}
func (m *ListRestaurantByEntityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRestaurantByEntityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRestaurantByEntityRequest proto.InternalMessageInfo

func (m *ListRestaurantByEntityRequest) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

type ListRestaurantByEntityResponse struct {
	Restaurants          []*Restaurant `protobuf:"bytes,1,rep,name=restaurants,proto3" json:"restaurants,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListRestaurantByEntityResponse) Reset()         { *m = ListRestaurantByEntityResponse{} }
func (m *ListRestaurantByEntityResponse) String() string { return proto.CompactTextString(m) }
func (*ListRestaurantByEntityResponse) ProtoMessage()    {}
func (*ListRestaurantByEntityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9528536a6390faa1, []int{7}
}

func (m *ListRestaurantByEntityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRestaurantByEntityResponse.Unmarshal(m, b)
}
func (m *ListRestaurantByEntityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRestaurantByEntityResponse.Marshal(b, m, deterministic)
}
func (m *ListRestaurantByEntityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRestaurantByEntityResponse.Merge(m, src)
}
func (m *ListRestaurantByEntityResponse) XXX_Size() int {
	return xxx_messageInfo_ListRestaurantByEntityResponse.Size(m)
}
func (m *ListRestaurantByEntityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRestaurantByEntityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRestaurantByEntityResponse proto.InternalMessageInfo

func (m *ListRestaurantByEntityResponse) GetRestaurants() []*Restaurant {
	if m != nil {
		return m.Restaurants
	}
	return nil
}

type RemoveRestaurantRequest struct {
	RestaurantId         string   `protobuf:"bytes,1,opt,name=restaurant_id,proto3" json:"restaurant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRestaurantRequest) Reset()         { *m = RemoveRestaurantRequest{} }
func (m *RemoveRestaurantRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveRestaurantRequest) ProtoMessage()    {}
func (*RemoveRestaurantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9528536a6390faa1, []int{8}
}

func (m *RemoveRestaurantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRestaurantRequest.Unmarshal(m, b)
}
func (m *RemoveRestaurantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRestaurantRequest.Marshal(b, m, deterministic)
}
func (m *RemoveRestaurantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRestaurantRequest.Merge(m, src)
}
func (m *RemoveRestaurantRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveRestaurantRequest.Size(m)
}
func (m *RemoveRestaurantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRestaurantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRestaurantRequest proto.InternalMessageInfo

func (m *RemoveRestaurantRequest) GetRestaurantId() string {
	if m != nil {
		return m.RestaurantId
	}
	return ""
}

type RemoveRestaurantResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRestaurantResponse) Reset()         { *m = RemoveRestaurantResponse{} }
func (m *RemoveRestaurantResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveRestaurantResponse) ProtoMessage()    {}
func (*RemoveRestaurantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9528536a6390faa1, []int{9}
}

func (m *RemoveRestaurantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRestaurantResponse.Unmarshal(m, b)
}
func (m *RemoveRestaurantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRestaurantResponse.Marshal(b, m, deterministic)
}
func (m *RemoveRestaurantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRestaurantResponse.Merge(m, src)
}
func (m *RemoveRestaurantResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveRestaurantResponse.Size(m)
}
func (m *RemoveRestaurantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRestaurantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRestaurantResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Address)(nil), "Address")
	proto.RegisterType((*Restaurant)(nil), "Restaurant")
	proto.RegisterType((*AddRestaurantRequest)(nil), "AddRestaurantRequest")
	proto.RegisterType((*AddRestaurantResponse)(nil), "AddRestaurantResponse")
	proto.RegisterType((*UpdateRestaurantRequest)(nil), "UpdateRestaurantRequest")
	proto.RegisterType((*UpdateRestaurantResponse)(nil), "UpdateRestaurantResponse")
	proto.RegisterType((*ListRestaurantByEntityRequest)(nil), "ListRestaurantByEntityRequest")
	proto.RegisterType((*ListRestaurantByEntityResponse)(nil), "ListRestaurantByEntityResponse")
	proto.RegisterType((*RemoveRestaurantRequest)(nil), "RemoveRestaurantRequest")
	proto.RegisterType((*RemoveRestaurantResponse)(nil), "RemoveRestaurantResponse")
}

func init() { proto.RegisterFile("restaurant.proto", fileDescriptor_9528536a6390faa1) }

var fileDescriptor_9528536a6390faa1 = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x5d, 0x4b, 0xfb, 0x30,
	0x18, 0xc5, 0x49, 0xb7, 0xff, 0x5e, 0x9e, 0xf2, 0x17, 0x09, 0xca, 0xe2, 0xd0, 0x51, 0x82, 0x17,
	0x03, 0xb1, 0xc2, 0xbc, 0x16, 0xd9, 0xf0, 0xed, 0x42, 0x10, 0x0a, 0xde, 0x78, 0x33, 0xe2, 0x12,
	0x24, 0xb0, 0xb5, 0xb5, 0x49, 0x85, 0x7e, 0x63, 0x3f, 0x86, 0x34, 0xed, 0x96, 0x6e, 0xb5, 0xa0,
	0xde, 0xa5, 0xe7, 0xa4, 0xe7, 0xf9, 0x9d, 0xa7, 0x14, 0xf6, 0x13, 0xa1, 0x34, 0x4b, 0x13, 0x16,
	0x6a, 0x3f, 0x4e, 0x22, 0x1d, 0xd1, 0x0c, 0xba, 0x53, 0xce, 0x13, 0xa1, 0x14, 0xc6, 0xd0, 0x0e,
	0xd9, 0x4a, 0x10, 0xe4, 0xa1, 0x71, 0x3f, 0x30, 0x67, 0xec, 0x81, 0xcb, 0x85, 0x5a, 0x24, 0x32,
	0xd6, 0x32, 0x0a, 0x89, 0x63, 0xac, 0xaa, 0x84, 0x8f, 0xa1, 0xbf, 0x8c, 0xc2, 0x37, 0xa9, 0x53,
	0x2e, 0x48, 0xcb, 0x43, 0x63, 0x14, 0x58, 0x01, 0x0f, 0xa1, 0xb7, 0x64, 0xba, 0x30, 0xdb, 0xc6,
	0xdc, 0x3c, 0xd3, 0x4f, 0x04, 0x10, 0x6c, 0x78, 0xf0, 0x1e, 0x38, 0x92, 0x97, 0xc3, 0x1d, 0xc9,
	0xf3, 0x60, 0x11, 0x6a, 0xa9, 0xb3, 0xb9, 0xe4, 0xe5, 0x60, 0x2b, 0x6c, 0x60, 0x5b, 0xcd, 0xb0,
	0xed, 0x3a, 0x2c, 0x85, 0x2e, 0x2b, 0xda, 0x92, 0x7f, 0x1e, 0x1a, 0xbb, 0x93, 0x9e, 0x5f, 0xb6,
	0x0f, 0xd6, 0x46, 0x9e, 0xac, 0xb3, 0x58, 0x90, 0x4e, 0x91, 0x9c, 0x9f, 0xf1, 0x08, 0x60, 0x91,
	0x08, 0xa6, 0x05, 0x9f, 0x33, 0x4d, 0xba, 0xc6, 0xa9, 0x28, 0xb9, 0x9f, 0xc6, 0x7c, 0xed, 0xf7,
	0x0a, 0xdf, 0x2a, 0xf4, 0x01, 0x0e, 0xa6, 0x9c, 0xdb, 0xb2, 0x81, 0x78, 0x4f, 0x85, 0xd2, 0xdb,
	0x1d, 0x51, 0x53, 0x47, 0xc7, 0x76, 0xa4, 0x37, 0x70, 0xb8, 0x93, 0xa4, 0xe2, 0x28, 0x54, 0x02,
	0x9f, 0x01, 0xd8, 0x8f, 0x6b, 0xb2, 0xdc, 0x89, 0xeb, 0x57, 0x2e, 0x56, 0x6c, 0x7a, 0x07, 0x83,
	0x67, 0x43, 0x57, 0x47, 0xfa, 0x55, 0xce, 0x3d, 0x90, 0x7a, 0xce, 0x5f, 0x80, 0xae, 0xe0, 0xe4,
	0x51, 0x2a, 0x6d, 0xdd, 0x59, 0x76, 0x6b, 0xf6, 0xf0, 0xa3, 0x4d, 0xd1, 0x27, 0x18, 0x35, 0xbd,
	0x5e, 0xd2, 0x9c, 0x83, 0x6b, 0xc7, 0x29, 0x82, 0xbc, 0xd6, 0x2e, 0x4e, 0xd5, 0xa7, 0xd7, 0x30,
	0x08, 0xc4, 0x2a, 0xfa, 0xf8, 0x66, 0x41, 0xa7, 0xf0, 0xdf, 0xde, 0xb4, 0x34, 0xdb, 0x22, 0x1d,
	0x02, 0xa9, 0x07, 0x14, 0x2c, 0xb3, 0xa3, 0x97, 0x81, 0x7f, 0x51, 0xb9, 0x6e, 0x8f, 0xaf, 0x1d,
	0xf3, 0x57, 0x5e, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0x36, 0xb6, 0x14, 0xd6, 0xa9, 0x03, 0x00,
	0x00,
}
